### ISSUE TITLE
Missing default sort icon

### ISSUE THREAD

**Issue by karlbaker02** [openregister/registers-frontend#192]
### What did you do? (steps to reproduce)

Go to the Registers collection page from the homepage. The registers on this page look to be sorted descending on `status`

### What happened? (actual results)

There is no default sort icon (as there is when you go to a particular register page) to specify that `status` has been sorted descending.

### What should have happened? (expected results)

Sort icon header should be present.

<img width="834" alt="screen shot 2018-02-21 at 10 22 14" src="https://user-images.githubusercontent.com/5422487/36475006-4a2dd2f0-16f1-11e8-88fa-bde1fec9ecf7.png">

**Comment by injms** [comment]
Thank you for raising this. I agree - there needs to be something to show which column is doing the sorting. However, the registers collection page has undergone a couple of iterations since this ticket was raised - now they're sorted by [category](https://www.registers.service.gov.uk/registers?show_by=category), [publishing organisation](https://www.registers.service.gov.uk/registers?show_by=organisation), and [name](https://www.registers.service.gov.uk/registers?show_by=name). These show the registers in a grid or a simpler list, neither of which can have their sorting changed.

With that in mind, I'm going to close this issue since it's out of date.
