### ISSUE TITLE
Remove question about Government work

### ISSUE THREAD

**Issue by edent** [openregister/registers-frontend#330]
### What did you do? (steps to reproduce)
Was asked "Do you work for government?" when registering for an API key.

Why do you need to know? Do contractors count? Do you mean the UK Government? What if I do, but am accessing for a personal project? 

### What happened? (actual results)
Does my email address end `.gov.uk`? If so, I probably work for the government.

### What should have happened? (expected results)

1. Remove the requirement to register with an email address
1. In the *optional* email field, use heuristics to determine if it is a government account.

**Comment by injms** [comment]
I'm closing this issue because a key is no longer needed when using the API, so registering isn't required. The optional questionnaire form no longer asks for a government email address, and is easily skippable. I hope this is okay - feel free to re-open or raise another issue if you think it's needed.

**Comment by edent** [comment]
Woo! Thanks.
